use demo;

CREATE TABLE employee
(
  EMPLOYEE_ID BIGINT AUTO_INCREMENT,
  NAME        VARCHAR(100),
  SALARY      BIGINT,
  BIRTHDAY    TIMESTAMP,
  HIREDATE    TIMESTAMP,
  LEVEL       TINYINT,
  DEPARTMENT  VARCHAR(100),
  PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE education
(
  EDUCATION_ID BIGINT AUTO_INCREMENT,
  EMPLOYEE_ID  BIGINT,
  SCHOOL       VARCHAR(100),
  MAJOR        VARCHAR(100),
  START        TIMESTAMP,
  graduate     TIMESTAMP,
  PRIMARY KEY (EDUCATION_ID)
);