CREATE DATABASE IF NOT EXISTS mybatis_parameter;

USE mybatis_parameter;

CREATE TABLE employee
(
  EMPLOYEE_ID BIGINT AUTO_INCREMENT,
  NAME        VARCHAR(100),
  SALARY      BIGINT,
  BIRTHDAY    TIMESTAMP,
  HIREDATE    TIMESTAMP,
  LEVEL       TINYINT,
  DEPARTMENT  VARCHAR(100),
  PRIMARY KEY (EMPLOYEE_ID)
);